spring:
  application:
    name: Growth
  datasource:
    url: jdbc:h2:mem:springdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      database-platform:
        org.hibernate.dialect.H2Dialect

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

queue:
  name: order